/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SkyApi
 * Notes: PET, RUNE and POTION item tags (somtimes called ids) are expanded to include the type, eg PET_LION.<br> All other Tags match with hypixel and can be found via the search endpoint, also see our <a href="https://sky.coflnet.com/wiki/api">api docs</a>.<br>Most of these endpoints are used for our <a href="https://sky.coflnet.com/flips">Hypixel skyblock ah and bazaar flipping service</a> and may need you to have a premium account token<br>Also if you use the api for a public project you are responsible for complying with our <a href="https://sky.coflnet.com/wiki/api#attribution">api attribution</a>.
 * OpenAPI spec version: v1
 */
export interface ActivePet {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  colorCode?: string | null;
  /** @nullable */
  progressPercent?: number | null;
  /** @nullable */
  targetLevel?: number | null;
  lastUpdated: string;
}

export interface AdvancedAnalysisResult {
  /** @nullable */
  volumeBuckets?: VolumeBucket[] | null;
  /** @nullable */
  sellSpeedBuckets?: SellSpeedBucket[] | null;
  totalSales: number;
  avgSellTimeSeconds: number;
  medianSellTimeSeconds: number;
  avgPrice: number;
  medianPrice: number;
  minPrice: number;
  maxPrice: number;
  binPercentage: number;
  salesPerDay: number;
  /** @nullable */
  hourlyBreakdown?: HourlyStat[] | null;
  priceStdDev: number;
  priceCoeffVariation: number;
  /** @nullable */
  topSellers?: SellerShare[] | null;
}

/**
 * @nullable
 */
export type ApiSaveAuctionFlatNbt = {[key: string]: string | null} | null;

export interface ApiSaveAuction {
  /** @nullable */
  flatNbt: ApiSaveAuctionFlatNbt;
  /** @nullable */
  uuid?: string | null;
  count: number;
  startingBid: number;
  /**
   * @maxLength 40
   * @nullable
   */
  tag?: string | null;
  /**
   * @maxLength 45
   * @nullable
   */
  itemName?: string | null;
  start: string;
  end: string;
  /** @nullable */
  auctioneerId?: string | null;
  /** @nullable */
  profileId?: string | null;
  /** @nullable */
  coop?: string[] | null;
  /** @nullable */
  coopMembers?: UuId[] | null;
  highestBidAmount: number;
  /** @nullable */
  bids?: SaveBids[] | null;
  anvilUses: number;
  /** @nullable */
  enchantments?: Enchantment[] | null;
  nbtData?: NbtData;
  itemCreatedAt: string;
  reforge: Reforge;
  category: Category;
  tier: Tier;
  bin: boolean;
}

export interface ArchiveResponse {
  /**
   * The auctions that were found
   * @nullable
   */
  auctions?: AuctionPreview[] | null;
  queryStatus: QueryStatus;
}

export interface AttributeFlip {
  /** @nullable */
  tag?: string | null;
  /** @nullable */
  itemName?: string | null;
  /** @nullable */
  auctionToBuy?: string | null;
  auctionPrice: number;
  profitAfterTax: number;
  /** @nullable */
  ingredients?: AttributeFlipIngredient[] | null;
  startingKey?: AttributeFlipAuctionKey;
  endingKey?: AttributeFlipAuctionKey;
  target: number;
  estimatedCraftingCost: number;
  foundAt: string;
  volume: number;
}

export interface AttributeFlipAuctionKey {
  /** @nullable */
  reforge?: string | null;
  tier?: Tier;
  /** @nullable */
  enchants?: AttributeFlipEnchant[] | null;
  /** @nullable */
  modifiers?: AttributeFlipModifier[] | null;
  count: number;
}

export interface AttributeFlipEnchant {
  /** @nullable */
  type?: string | null;
  lvl: number;
}

export interface AttributeFlipIngredient {
  /** @nullable */
  itemId?: string | null;
  /** @nullable */
  attributeName?: string | null;
  amount: number;
  price: number;
}

export interface AttributeFlipModifier {
  /** @nullable */
  key?: string | null;
  /** @nullable */
  value?: string | null;
}

export interface AuctionPreview {
  /** @nullable */
  seller: string | null;
  price: number;
  end: string;
  /** @nullable */
  uuid: string | null;
  /** @nullable */
  playerName: string | null;
}

export interface AuctionResult {
  /** @nullable */
  auctionId: string | null;
  highestBid: number;
  /** @nullable */
  itemName: string | null;
  /** @nullable */
  tag: string | null;
  end: string;
  startingBid: number;
  bin: boolean;
}

export interface Autopet {
  rules_limit: number;
}

export interface AveragePrice {
  min: number;
  max: number;
  avg: number;
  volume: number;
  time: string;
}

export interface BagContents {
  potion_bag?: InventoryElem;
  talisman_bag?: InventoryElem;
  fishing_bag?: InventoryElem;
  quiver?: InventoryElem;
}

export interface Banking {
  balance: number;
}

export interface BatchProductPricingResponse {
  /** @nullable */
  creatorCode?: string | null;
  discountPercent: number;
  /** @nullable */
  products?: ProductPricingResponse[] | null;
}

export interface BazaarFlip {
  /** @nullable */
  itemTag?: string | null;
  buyPrice: number;
  sellPrice: number;
  profitPerHour: number;
  volume: number;
  estimatedFees: number;
  timestamp: string;
  medianBuyPrice: number;
  estimatedBuyFillSeconds: number;
  estimatedSellFillSeconds: number;
}

/**
 * Paginated bid result for player overview
 */
export interface BidResult {
  /** The highest bid the requesting player has made */
  highestOwnBid: number;
  /** @nullable */
  auctionId: string | null;
  highestBid: number;
  /** @nullable */
  itemName: string | null;
  /** @nullable */
  tag: string | null;
  end: string;
  startingBid: number;
  bin: boolean;
}

/**
 * Lowest bin response
 */
export interface BinResponse {
  /** The lowest bin price */
  lowest: number;
  /**
   * The lowest bin auction uuid
   * @nullable
   */
  uuid: string | null;
  /** The price of the second lowest bin */
  secondLowest: number;
}

export interface BlockPos {
  x: number;
  y: number;
  z: number;
}

export interface BookFlip {
  /** @nullable */
  startTag?: string | null;
  /** @nullable */
  endTag?: string | null;
  profitPerHour: number;
  hourlyVolume: number;
  estimatedFees: number;
  timestamp: string;
}

export type Category = typeof Category[keyof typeof Category];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Category = {
  UNKNOWN: 'UNKNOWN',
  WEAPON: 'WEAPON',
  ARMOR: 'ARMOR',
  ACCESSORIES: 'ACCESSORIES',
  CONSUMABLES: 'CONSUMABLES',
  BLOCKS: 'BLOCKS',
  MISC: 'MISC',
  cosmetic: 'cosmetic',
  dyes: 'dyes',
} as const;

export interface CoflnetSkyMayorModelsMinister {
  /** @nullable */
  key?: string | null;
  /** @nullable */
  name?: string | null;
  perk?: CoflnetSkyMayorModelsPerk;
}

export interface CoflnetSkyMayorModelsModelCandidate {
  /** @nullable */
  key?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  perks?: CoflnetSkyMayorModelsModelPerk[] | null;
  votes: number;
}

export interface CoflnetSkyMayorModelsModelElectionPeriod {
  /** @nullable */
  candidates?: CoflnetSkyMayorModelsModelCandidate[] | null;
  /** @nullable */
  end?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  start?: string | null;
  winner?: CoflnetSkyMayorModelsModelWinner;
  year: number;
}

export interface CoflnetSkyMayorModelsModelPerk {
  /** @nullable */
  description?: string | null;
  /** @nullable */
  name?: string | null;
  minister: boolean;
}

export interface CoflnetSkyMayorModelsModelWinner {
  minister?: CoflnetSkyMayorModelsMinister;
  /** @nullable */
  key?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  perks?: CoflnetSkyMayorModelsModelPerk[] | null;
  votes: number;
}

export interface CoflnetSkyMayorModelsPerk {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  minister: boolean;
}

export interface CoinTransaction {
  /** @nullable */
  productId?: string | null;
  /** @nullable */
  reference?: string | null;
  amount: number;
  timeStamp: string;
}

export interface ColorEnchant {
  /** @nullable */
  color: string | null;
  value: number;
  type: EnchantmentType;
  level: number;
}

/**
 * @nullable
 */
export type ColorSaveAuctionFlatNbt = {[key: string]: string | null} | null;

export interface ColorSaveAuction {
  /** @nullable */
  enchantments?: ColorEnchant[] | null;
  /** @nullable */
  uuid?: string | null;
  count: number;
  startingBid: number;
  /**
   * @maxLength 40
   * @nullable
   */
  tag?: string | null;
  /**
   * @maxLength 45
   * @nullable
   */
  itemName?: string | null;
  start: string;
  end: string;
  /** @nullable */
  auctioneerId?: string | null;
  /** @nullable */
  profileId?: string | null;
  /** @nullable */
  coop?: string[] | null;
  /** @nullable */
  coopMembers?: UuId[] | null;
  highestBidAmount: number;
  /** @nullable */
  bids?: SaveBids[] | null;
  anvilUses: number;
  nbtData?: NbtData;
  itemCreatedAt: string;
  reforge: Reforge;
  category: Category;
  tier: Tier;
  bin: boolean;
  /** @nullable */
  flatNbt: ColorSaveAuctionFlatNbt;
}

/**
 * Represents help text for some command
 */
export interface CommandListEntry {
  /**
   * The commands label. ie /cofl {this}
   * @nullable
   */
  subCommand: string | null;
  /**
   * The descriptive help text to display
   * @nullable
   */
  description: string | null;
}

export interface CompletedBazaarFlip {
  playerUuid: string;
  year: number;
  /** @nullable */
  itemTag?: string | null;
  /** @nullable */
  itemName?: string | null;
  amount: number;
  buyPrice: number;
  sellPrice: number;
  profit: number;
  soldAt: string;
}

export interface Composter {
  nextCompostAt: string;
  fuelStored: number;
  matterStored: number;
  lastCompostToClaim: number;
  speedPercentIncrease: number;
  multiDropChance: number;
  fuelCap: number;
  matterCap: number;
  costReductionPercent: number;
}

export interface CopperFlip {
  /** @nullable */
  itemTag?: string | null;
  buyPrice: number;
  analyzeCost: number;
  copperYield: number;
  totalCost: number;
  copperPerCoin: number;
  timestamp: string;
  volume: number;
}

export interface Cost {
  /** @nullable */
  itemName?: string | null;
  price: number;
  amount: number;
  /** @nullable */
  itemTag?: string | null;
}

/**
 * @nullable
 */
export type CraftInstructionRecipe = {[key: string]: string | null} | null;

/**
 * @nullable
 */
export type CraftInstructionCopyCommands = {[key: string]: string | null} | null;

/**
 * @nullable
 */
export type CraftInstructionDetailsPath = {[key: string]: string | null} | null;

export interface CraftInstruction {
  /** @nullable */
  itemTag?: string | null;
  /** @nullable */
  recipe?: CraftInstructionRecipe;
  /** @nullable */
  copyCommands?: CraftInstructionCopyCommands;
  /** @nullable */
  detailsPath?: CraftInstructionDetailsPath;
}

export interface CraftPrice {
  price: number;
  /** @nullable */
  itemTag: string | null;
  /** @nullable */
  attribute: string | null;
  /** @nullable */
  formattedReson: string | null;
  count: number;
}

/**
 * @nullable
 */
export type CurrenciesEssence = {[key: string]: EssenceAmount} | null;

export interface Currencies {
  coin_purse: number;
  motes_purse: number;
  /** @nullable */
  essence?: CurrenciesEssence;
}

export interface CurrentPrice {
  sell: number;
  buy: number;
  available: number;
  updatedAt: string;
  isAh: boolean;
}

export interface DemandFlip {
  /** @nullable */
  itemTag?: string | null;
  currentProfitPerHour: number;
  timestamp: string;
  volume: number;
  buyPrice: number;
  sellPrice: number;
  medianValue: number;
}

export interface DemandSpreadFlip {
  flip?: DemandFlip;
  /** @nullable */
  itemName?: string | null;
}

/**
 * Response object instructing minecraft mods how to modify the description
 */
export interface DescModification {
  type: ModType;
  /** Extra field containing index to insert (int), or value to replace (string) */
  line: number;
  /**
   * New value to add,insert, or replace something with
   * @nullable
   */
  value?: string | null;
}

export type DescriptionField = typeof DescriptionField[keyof typeof DescriptionField];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DescriptionField = {
  NONE: 'NONE',
  LBIN: 'LBIN',
  LBIN_KEY: 'LBIN_KEY',
  MEDIAN: 'MEDIAN',
  MEDIAN_KEY: 'MEDIAN_KEY',
  VOLUME: 'VOLUME',
  TAG: 'TAG',
  CRAFT_COST: 'CRAFT_COST',
  BazaarBuy: 'BazaarBuy',
  BazaarSell: 'BazaarSell',
  PRICE_PAID: 'PRICE_PAID',
  ITEM_KEY: 'ITEM_KEY',
  EnchantCost: 'EnchantCost',
  GemValue: 'GemValue',
  SpentOnAhFees: 'SpentOnAhFees',
  KatUpgradeCost: 'KatUpgradeCost',
  InstaSellPrice: 'InstaSellPrice',
  ModifierCost: 'ModifierCost',
  FullCraftCost: 'FullCraftCost',
  ModifierCostList: 'ModifierCostList',
  FinderEstimates: 'FinderEstimates',
  Volatility: 'Volatility',
  LastSoldFor: 'LastSoldFor',
  TimeToSell: 'TimeToSell',
  NpcSellPrice: 'NpcSellPrice',
  ColorCode: 'ColorCode',
  DefaultLore: 'DefaultLore',
  AiEstimate: 'AiEstimate',
  BAZAAR_COST: 'BAZAAR_COST',
} as const;

export interface DescriptionSetting {
  highlightFilterMatch: boolean;
  minProfitForHighlight: number;
  disableHighlighting: boolean;
  disableSuggestions: boolean;
  /** @nullable */
  disableInfoIn: string[] | null;
  disabled: boolean;
  lowballMedUndercut: number;
  lowballLbinUndercut: number;
  preferLbinInSuggestions: boolean;
  suggestQuicksell: boolean;
  /** @nullable */
  replaceGrayWith: string | null;
  /** @nullable */
  replaceAquaWith: string | null;
  /** @nullable */
  replaceYellowWith: string | null;
  /** @nullable */
  replaceGoldWith: string | null;
  /** @nullable */
  replaceWhiteWith: string | null;
  noCookie: boolean;
  buyOrderPrices: boolean;
  disableAuctionStartedTime: boolean;
  /** @nullable */
  fields?: DescriptionField[][] | null;
  highlightInfo?: HighlightInfo;
}

/**
 * @nullable
 */
export type DiscordMessageAttachments = {[key: string]: string} | null;

export interface DiscordMessage {
  channelId: number;
  messageId: number;
  /** @nullable */
  content?: string | null;
  createdAt: string;
  month: number;
  /** @nullable */
  attachments?: DiscordMessageAttachments;
  /** @nullable */
  authorName?: string | null;
  authorId: number;
  updateAt: string;
}

export interface DropStatistic {
  monthly: number;
  recent: number;
  /** @nullable */
  tag?: string | null;
  volume: number;
  lastUpdated: string;
  now: number;
}

export interface Enchantment {
  type: EnchantmentType;
  level: number;
}

export type EnchantmentType = typeof EnchantmentType[keyof typeof EnchantmentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnchantmentType = {
  unknown: 'unknown',
  cleave: 'cleave',
  critical: 'critical',
  cubism: 'cubism',
  ender_slayer: 'ender_slayer',
  execute: 'execute',
  experience: 'experience',
  first_strike: 'first_strike',
  giant_killer: 'giant_killer',
  impaling: 'impaling',
  lethality: 'lethality',
  life_steal: 'life_steal',
  luck: 'luck',
  scavenger: 'scavenger',
  thunderlord: 'thunderlord',
  telekinesis: 'telekinesis',
  vampirism: 'vampirism',
  venomous: 'venomous',
  growth: 'growth',
  aiming: 'aiming',
  dragon_hunter: 'dragon_hunter',
  infinite_quiver: 'infinite_quiver',
  piercing: 'piercing',
  snipe: 'snipe',
  harvesting: 'harvesting',
  rainbow: 'rainbow',
  smelting_touch: 'smelting_touch',
  angler: 'angler',
  blessing: 'blessing',
  caster: 'caster',
  frail: 'frail',
  magnet: 'magnet',
  spiked_hook: 'spiked_hook',
  bane_of_arthropods: 'bane_of_arthropods',
  fire_aspect: 'fire_aspect',
  looting: 'looting',
  knockback: 'knockback',
  sharpness: 'sharpness',
  smite: 'smite',
  aqua_affinity: 'aqua_affinity',
  blast_protection: 'blast_protection',
  depth_strider: 'depth_strider',
  feather_falling: 'feather_falling',
  fire_protection: 'fire_protection',
  frost_walker: 'frost_walker',
  projectile_protection: 'projectile_protection',
  protection: 'protection',
  respiration: 'respiration',
  thorns: 'thorns',
  flame: 'flame',
  power: 'power',
  punch: 'punch',
  efficiency: 'efficiency',
  fortune: 'fortune',
  silk_touch: 'silk_touch',
  lure: 'lure',
  luck_of_the_sea: 'luck_of_the_sea',
  true_protection: 'true_protection',
  sugar_rush: 'sugar_rush',
  replenish: 'replenish',
  rejuvenate: 'rejuvenate',
  ultimate_bank: 'ultimate_bank',
  ultimate_combo: 'ultimate_combo',
  ultimate_jerry: 'ultimate_jerry',
  ultimate_last_stand: 'ultimate_last_stand',
  ultimate_no_pain_no_gain: 'ultimate_no_pain_no_gain',
  ultimate_wisdom: 'ultimate_wisdom',
  ultimate_wise: 'ultimate_wise',
  expertise: 'expertise',
  ultimate_chimera: 'ultimate_chimera',
  ultimate_rend: 'ultimate_rend',
  overload: 'overload',
  ultimate_legion: 'ultimate_legion',
  ultimate_swarm: 'ultimate_swarm',
  big_brain: 'big_brain',
  compact: 'compact',
  vicious: 'vicious',
  counter_strike: 'counter_strike',
  turbo_carrot: 'turbo_carrot',
  turbo_cactus: 'turbo_cactus',
  turbo_cane: 'turbo_cane',
  turbo_coco: 'turbo_coco',
  turbo_melon: 'turbo_melon',
  turbo_mushrooms: 'turbo_mushrooms',
  turbo_pumpkin: 'turbo_pumpkin',
  turbo_potato: 'turbo_potato',
  turbo_warts: 'turbo_warts',
  turbo_wheat: 'turbo_wheat',
  chance: 'chance',
  prosecute: 'prosecute',
  syphon: 'syphon',
  respite: 'respite',
  thunderbolt: 'thunderbolt',
  titan_killer: 'titan_killer',
  triple_strike: 'triple_strike',
  ultimate_soul_eater: 'ultimate_soul_eater',
  ultimate_one_for_all: 'ultimate_one_for_all',
  None: 'None',
  cultivating: 'cultivating',
  delicate: 'delicate',
  mana_steal: 'mana_steal',
  smarty_pants: 'smarty_pants',
  pristine: 'pristine',
  ultimate_fatal_tempo: 'ultimate_fatal_tempo',
  ultimate_inferno: 'ultimate_inferno',
  charm: 'charm',
  corruption: 'corruption',
  ferocious_mana: 'ferocious_mana',
  strong_mana: 'strong_mana',
  hardened_mana: 'hardened_mana',
  mana_vampire: 'mana_vampire',
  smoldering: 'smoldering',
  ultimate_reiterate: 'ultimate_reiterate',
  ultimate_flash: 'ultimate_flash',
  hecatomb: 'hecatomb',
  champion: 'champion',
  ultimate_habanero_tactics: 'ultimate_habanero_tactics',
  cayenne: 'cayenne',
  divine_gift: 'divine_gift',
  piscary: 'piscary',
  ultimate_bobbin_time: 'ultimate_bobbin_time',
  tabasco: 'tabasco',
  prosperity: 'prosperity',
  sunder: 'sunder',
  dedication: 'dedication',
  Any: 'Any',
  green_thumb: 'green_thumb',
  transylvanian: 'transylvanian',
  reflection: 'reflection',
  ultimate_the_one: 'ultimate_the_one',
  quantum: 'quantum',
  pesterminator: 'pesterminator',
  great_spook: 'great_spook',
  ultimate_refrigerate: 'ultimate_refrigerate',
  paleontologist: 'paleontologist',
  ice_cold: 'ice_cold',
  toxophilite: 'toxophilite',
  ultimate_flowstate: 'ultimate_flowstate',
  lapidary: 'lapidary',
  small_brain: 'small_brain',
  tidal: 'tidal',
  quick_bite: 'quick_bite',
  absorb: 'absorb',
  arcane: 'arcane',
  drainRenamed: 'drainRenamed',
  ultimate_first_impression: 'ultimate_first_impression',
  forest_pledge: 'forest_pledge',
  ultimate_missile: 'ultimate_missile',
  raspiration: 'raspiration',
  scuba: 'scuba',
  stealth: 'stealth',
  ultimate_crop_fever: 'ultimate_crop_fever',
  turbo_sunflower: 'turbo_sunflower',
  turbo_moonflower: 'turbo_moonflower',
  turbo_rose: 'turbo_rose',
} as const;

export interface ErrorResponse {
  /** @nullable */
  slug?: string | null;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  trace?: string | null;
}

export interface EssenceAmount {
  current: number;
}

export type ExportFlags = typeof ExportFlags[keyof typeof ExportFlags];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportFlags = {
  None: 'None',
  IncludeSocial: 'IncludeSocial',
  InventoryCheck: 'InventoryCheck',
  UniqueItems: 'UniqueItems',
} as const;

/**
 * @nullable
 */
export type ExportRequestFilters = {[key: string]: string} | null;

export interface ExportRequest {
  flags?: ExportFlags;
  status?: ExportStatus;
  /** @nullable */
  byEmail?: string | null;
  /** @nullable */
  discordWebhookUrl?: string | null;
  requestedAt: string;
  /** @nullable */
  itemTag?: string | null;
  /** @nullable */
  filters?: ExportRequestFilters;
  /** @nullable */
  columns?: string[] | null;
  /** @nullable */
  s3Url?: string | null;
}

/**
 * @nullable
 */
export type ExportRequestCreateFilters = {[key: string]: string | null} | null;

export interface ExportRequestCreate {
  flags: ExportFlags;
  /** @nullable */
  filters?: ExportRequestCreateFilters;
  /** @nullable */
  discordWebhookUrl?: string | null;
}

export type ExportStatus = typeof ExportStatus[keyof typeof ExportStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportStatus = {
  Pending: 'Pending',
  InProgress: 'InProgress',
  Done: 'Done',
  Failed: 'Failed',
  Cancelled: 'Cancelled',
} as const;

/**
 * @nullable
 */
export type ExtractedInfoShardCounts = {[key: string]: number} | null;

/**
 * @nullable
 */
export type ExtractedInfoAttributeLevel = {[key: string]: number} | null;

export interface ExtractedInfo {
  boosterCookieExpires: string;
  kuudraStart: string;
  katStatus?: KatStatus;
  /** @nullable */
  forgeItems?: ForgeItem[] | null;
  /** @nullable */
  currentServer?: string | null;
  /** @nullable */
  currentLocation?: string | null;
  lastLocationChange: string;
  heartOfTheMountain?: HeartOfThe;
  heartOfTheForest?: HeartOfThe;
  agathaLevel: number;
  /** @nullable */
  shardCounts?: ExtractedInfoShardCounts;
  /** @nullable */
  attributeLevel?: ExtractedInfoAttributeLevel;
  composter?: Composter;
  activePet?: ActivePet;
  /** @nullable */
  pets?: PetState[] | null;
  weaponInHuntaxe?: Item;
  /** @nullable */
  huntingToolkitItems?: Item[] | null;
  playerElectionVote?: PlayerElectionVote;
}

export interface Fill {
  /** @nullable */
  playerName?: string | null;
  amount: number;
  timeStamp: string;
}

export interface FilterOptions {
  /** @nullable */
  name: string | null;
  /** @nullable */
  options: string[] | null;
  type: FilterType;
  /** @nullable */
  longType: string | null;
  /** @nullable */
  description: string | null;
}

/**
 * @nullable
 */
export type FilterQueryFilters = {[key: string]: string | null} | null;

export interface FilterQuery {
  /** @nullable */
  filters?: FilterQueryFilters;
  auction?: ApiSaveAuction;
}

export type FilterType = typeof FilterType[keyof typeof FilterType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FilterType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_4: 4,
  NUMBER_8: 8,
  NUMBER_16: 16,
  NUMBER_32: 32,
  NUMBER_64: 64,
  NUMBER_128: 128,
  NUMBER_256: 256,
  NUMBER_512: 512,
  NUMBER_1024: 1024,
} as const;

export type FinderType = typeof FinderType[keyof typeof FinderType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FinderType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
  NUMBER_8: 8,
  NUMBER_16: 16,
  NUMBER_32: 32,
  NUMBER_64: 64,
  NUMBER_128: 128,
  NUMBER_239: 239,
  NUMBER_256: 256,
  NUMBER_512: 512,
  NUMBER_1024: 1024,
  NUMBER_2048: 2048,
  NUMBER_4096: 4096,
} as const;

export interface FlipDetails {
  /** @nullable */
  itemName: string | null;
  /** @nullable */
  itemTag: string | null;
  /** @nullable */
  tier: string | null;
  pricePaid: number;
  soldFor: number;
  finder: FinderType;
  uId: number;
  /** @nullable */
  originAuction: string | null;
  /** @nullable */
  soldAuction: string | null;
  buyTime: string;
  sellTime: string;
  profit: number;
  /** @nullable */
  propertyChanges: PropertyChange[] | null;
  flags: FlipFlags;
}

export type FlipFlags = typeof FlipFlags[keyof typeof FlipFlags];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FlipFlags = {
  None: 'None',
  DifferentBuyer: 'DifferentBuyer',
  ViaTrade: 'ViaTrade',
  MultiItemTrade: 'MultiItemTrade',
} as const;

/**
 * @nullable
 */
export type FlipSettingsFilters = {[key: string]: string | null} | null;

export interface FlipSettings {
  /** @nullable */
  filters: FlipSettingsFilters;
  /** @nullable */
  blacklist: ListEntry[] | null;
  /** @nullable */
  whitelist: ListEntry[] | null;
  lbin: boolean;
  visibility: VisibilitySettings;
  mod: ModSettings;
  finders: FinderType;
  fastMode: boolean;
  /** @nullable */
  publishedAs: string | null;
  loadedVersion: number;
  /** @nullable */
  changer: string | null;
  onlyBin: boolean;
  whitelistAftermain: boolean;
  /** @nullable */
  basedConfig: string | null;
  blockExport: boolean;
  blockHighCompetition: boolean;
  minProfit: number;
  minProfitPercent: number;
  minVolume: number;
  maxCost: number;
  /** @nullable */
  lastChange: string | null;
}

export interface FlipSumary {
  /** @nullable */
  flips: FlipDetails[] | null;
  totalProfit: number;
}

/**
 * @nullable
 */
export type ForgeFlipRequirements = {[key: string]: number} | null;

export interface ForgeFlip {
  craftData?: ProfitableCraft;
  duration: number;
  requiredHotMLevel: number;
  profitPerHour: number;
  /** @nullable */
  requirements?: ForgeFlipRequirements;
}

export interface ForgeItem {
  /** @nullable */
  itemName?: string | null;
  forgeEnd: string;
  /** @nullable */
  tag?: string | null;
}

/**
 * @nullable
 */
export type FuseFlipInputs = {[key: string]: number} | null;

export interface FuseFlip {
  /** @nullable */
  inputs?: FuseFlipInputs;
  inputCost: number;
  volume: number;
  inputVolume: number;
  outputValue: number;
  /** @nullable */
  output?: string | null;
  outputCount: number;
  /** @nullable */
  steps?: FusionStep[] | null;
  depth: number;
}

/**
 * @nullable
 */
export type FusionStepInputs = {[key: string]: number} | null;

export interface FusionStep {
  /** @nullable */
  inputs?: FusionStepInputs;
  /** @nullable */
  output?: string | null;
  outputCount: number;
}

export interface GooglePlayPurchaseRequest {
  /** @nullable */
  productId: string | null;
  /** @nullable */
  purchaseToken: string | null;
  /** @nullable */
  packageName: string | null;
  /** @nullable */
  userId: string | null;
  /** @nullable */
  customAmount?: number | null;
}

export interface GraphResult {
  maxBuy: number;
  maxSell: number;
  minBuy: number;
  minSell: number;
  buy: number;
  sell: number;
  sellVolume: number;
  buyVolume: number;
  timestamp: string;
  buyMovingWeek: number;
  sellMovingWeek: number;
}

/**
 * @nullable
 */
export type HeartOfThePerks = {[key: string]: number} | null;

export interface HeartOfThe {
  tier: number;
  /** @nullable */
  perks?: HeartOfThePerks;
}

export interface HighlightInfo {
  position?: BlockPos;
  /** @nullable */
  hexColor?: string | null;
  slotId: number;
  /** @nullable */
  chestname?: string | null;
}

export interface HourlyStat {
  hour: number;
  count: number;
  avgPrice: number;
  avgSellTimeSeconds: number;
}

export interface Ingredient {
  /** @nullable */
  itemId?: string | null;
  count: number;
  cost: number;
  buyOrderCost: number;
  craftCost: number;
  /** @nullable */
  type?: string | null;
}

export interface Int32Int64ValueTuple {
  item1: number;
  item2: number;
}

/**
 * @nullable
 */
export type InventorySacksCounts = {[key: string]: number} | null;

/**
 * The backpack elements
 * @nullable
 */
export type InventoryBackpackIcons = {[key: string]: InventoryElem} | null;

/**
 * @nullable
 */
export type InventoryBackpackContents = {[key: string]: InventoryElem} | null;

export interface Inventory {
  inv_contents?: InventoryElem;
  inv_armor?: InventoryElem;
  ender_chest_contents?: InventoryElem;
  /** @nullable */
  ender_chest_page_icons?: unknown[] | null;
  equipment_contents?: InventoryElem;
  bag_contents?: BagContents;
  personal_vault_contents?: InventoryElem;
  wardrobe_equipped_slot: number;
  /** @nullable */
  sacks_counts?: InventorySacksCounts;
  wardrobe_contents?: InventoryElem;
  /**
   * The backpack elements
   * @nullable
   */
  backpack_icons?: InventoryBackpackIcons;
  /** @nullable */
  backpack_contents?: InventoryBackpackContents;
}

export interface InventoryBatchLookup {
  /** @nullable */
  profileId: string | null;
  /** @nullable */
  playerId: string | null;
  /** @nullable */
  uuids: string[] | null;
}

/**
 * Nbt formatted as json like mineflayer does it
 * @nullable
 */
export type InventoryDataJsonNbt = unknown | null;

/**
 * Representation of an inventory
 */
export interface InventoryData {
  /**
   * The name of the chest
   * @nullable
   */
  chestName: string | null;
  /**
   * Base64, gziped nbtdata of the inventory
   * @nullable
   */
  fullInventoryNbt: string | null;
  position: BlockPos;
  /**
   * Nbt formatted as json like mineflayer does it
   * @nullable
   */
  jsonNbt: InventoryDataJsonNbt;
  /**
   * Id of the sender to identify and or contact
   * @nullable
   */
  senderContactId: string | null;
}

/**
 * Nbt formatted as json like mineflayer does it
 * @nullable
 */
export type InventoryDataWithSettingsJsonNbt = unknown | null;

/**
 * Representation of an inventory with settings
 */
export interface InventoryDataWithSettings {
  /**
   * The name of the chest
   * @nullable
   */
  chestName: string | null;
  /**
   * Base64, gziped nbtdata of the inventory
   * @nullable
   */
  fullInventoryNbt: string | null;
  position: BlockPos;
  /**
   * Nbt formatted as json like mineflayer does it
   * @nullable
   */
  jsonNbt: InventoryDataWithSettingsJsonNbt;
  /**
   * Id of the sender to identify and or contact
   * @nullable
   */
  senderContactId: string | null;
  settings?: DescriptionSetting;
  /** Incremental version of the client library to know supported features */
  version: number;
}

export interface InventoryElem {
  type: number;
  /** @nullable */
  data?: string | null;
}

/**
 * @nullable
 */
export type ItemExtraAttributes = {[key: string]: unknown} | null;

/**
 * @nullable
 */
export type ItemEnchantments = {[key: string]: number} | null;

export interface Item {
  /** @nullable */
  id?: number | null;
  /** @nullable */
  itemName?: string | null;
  /** @nullable */
  tag?: string | null;
  /** @nullable */
  extraAttributes?: ItemExtraAttributes;
  /** @nullable */
  enchantments?: ItemEnchantments;
  /** @nullable */
  color?: number | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  count?: number | null;
}

export type ItemCategory = typeof ItemCategory[keyof typeof ItemCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemCategory = {
  UNKNOWN: 'UNKNOWN',
  PET_ITEM: 'PET_ITEM',
  SWORD: 'SWORD',
  CHESTPLATE: 'CHESTPLATE',
  HELMET: 'HELMET',
  REFORGE_STONE: 'REFORGE_STONE',
  COSMETIC: 'COSMETIC',
  AXE: 'AXE',
  LEGGINGS: 'LEGGINGS',
  ACCESSORY: 'ACCESSORY',
  BOW: 'BOW',
  TRAVEL_SCROLL: 'TRAVEL_SCROLL',
  BOOTS: 'BOOTS',
  HOE: 'HOE',
  BAIT: 'BAIT',
  FISHING_ROD: 'FISHING_ROD',
  DUNGEON_PASS: 'DUNGEON_PASS',
  ARROW: 'ARROW',
  SPADE: 'SPADE',
  SHEARS: 'SHEARS',
  PICKAXE: 'PICKAXE',
  ARROW_POISON: 'ARROW_POISON',
  WAND: 'WAND',
  DRILL: 'DRILL',
  FISHING_WEAPON: 'FISHING_WEAPON',
  GAUNTLET: 'GAUNTLET',
  FURNITURE: 'FURNITURE',
  GENERATOR: 'GENERATOR',
  MINION_SKIN: 'MINION_SKIN',
  PRIVATE_ISLAND: 'PRIVATE_ISLAND',
  ISLAND_CRYSTAL: 'ISLAND_CRYSTAL',
  FRAGMENT: 'FRAGMENT',
  SLAYER: 'SLAYER',
  DUNGEON: 'DUNGEON',
  DUNGEON_ITEM: 'DUNGEON_ITEM',
  SACK: 'SACK',
  PORTAL: 'PORTAL',
  DEEP_CAVERNS: 'DEEP_CAVERNS',
  BACKPACK: 'BACKPACK',
  TALISMAN_ENRICHMENT: 'TALISMAN_ENRICHMENT',
  THE_FISH: 'THE_FISH',
  PET: 'PET',
  PET_SKIN: 'PET_SKIN',
  RUNE: 'RUNE',
  ArmorDye: 'ArmorDye',
  Vanilla: 'Vanilla',
  NullNamed: 'NullNamed',
  CLOAK: 'CLOAK',
  NECKLACE: 'NECKLACE',
  BELT: 'BELT',
  GLOVES: 'GLOVES',
  BRACELET: 'BRACELET',
  InfernoMinionFuel: 'InfernoMinionFuel',
  MEMENTO: 'MEMENTO',
  ABIPHONE: 'ABIPHONE',
  Fossil: 'Fossil',
  FISHING_ROD_PART: 'FISHING_ROD_PART',
  VACUUM: 'VACUUM',
  CHISEL: 'CHISEL',
  FISHING_NET: 'FISHING_NET',
  LASSO: 'LASSO',
  TRAP: 'TRAP',
  DEPLOYABLE: 'DEPLOYABLE',
  LONGSWORD: 'LONGSWORD',
  BOOSTER: 'BOOSTER',
  CARNIVAL_MASK: 'CARNIVAL_MASK',
} as const;

export type ItemFlags = typeof ItemFlags[keyof typeof ItemFlags];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemFlags = {
  NONE: 'NONE',
  BAZAAR: 'BAZAAR',
  TRADEABLE: 'TRADEABLE',
  AUCTION: 'AUCTION',
  CRAFT: 'CRAFT',
  GLOWING: 'GLOWING',
  MUSEUM: 'MUSEUM',
  FIRESALE: 'FIRESALE',
} as const;

/**
 * Item Metadata
 */
export interface ItemMetadataElement {
  /**
   * The name of the element
   * @nullable
   */
  name?: string | null;
  /**
   * The hypixel tag of the item
   * @nullable
   */
  tag?: string | null;
  flags: ItemFlags;
}

export interface ItemPreview {
  /** @nullable */
  tag?: string | null;
  /** @nullable */
  name?: string | null;
}

/**
 * @nullable
 */
export type ItemRepresentExtraAttributes = {[key: string]: unknown} | null;

/**
 * @nullable
 */
export type ItemRepresentEnchantments = {[key: string]: number} | null;

export interface ItemRepresent {
  /** @nullable */
  id?: number | null;
  /** @nullable */
  itemName?: string | null;
  /** @nullable */
  tag?: string | null;
  /** @nullable */
  extraAttributes?: ItemRepresentExtraAttributes;
  /** @nullable */
  enchantments?: ItemRepresentEnchantments;
  /** @nullable */
  color?: number | null;
  /** @nullable */
  description?: string | null;
  count: number;
}

/**
 * Lookup element for sold items
 */
export interface ItemSell {
  /**
   * The minecraft account uuid that sold the item
   * @nullable
   */
  seller: string | null;
  /**
   * The hypixel auction uuid for the item
   * @nullable
   */
  uuid: string | null;
  /**
   * The minecraft account uuid that bought the item
   * @nullable
   */
  buyer: string | null;
  /**
   * Hypixel internal item id, can be used for retrieving image
   * @nullable
   */
  itemTag: string | null;
  /** The coin amount of the item that was sold for */
  highestBid: number;
  /** When was the item sold */
  timestamp: string;
}

/**
 * Kat pet rarity upgrade flip
 */
export interface KatFlip {
  /** 24 hour sell volume */
  volume: number;
  /** Median prie of the item */
  median: number;
  /** The amount of coins the upgrade costs (excluding materials) */
  readonly upgradeCost: number;
  /** The cost for materials at current bazaar/ah rate */
  readonly materialCost: number;
  /**
   * The auction to flip
   * @nullable
   */
  originAuction?: string | null;
  coreData?: KatUpgradeCost;
  targetRarity?: Tier;
  /** The estimated profit the flip will genreate */
  readonly profit: number;
  /**
   * The reference auction used to estimate the profit (lowest bin of higher rarity)
   * @nullable
   */
  referenceAuction?: string | null;
  /** How much the starting bid of the auction is */
  readonly purchaseCost: number;
  /**
   * The full name of the origin auction (cotnaining pet level)
   * @nullable
   */
  readonly originAuctionName?: string | null;
}

export interface KatStatus {
  isKatActive: boolean;
  katEnd: string;
  /** @nullable */
  itemName?: string | null;
}

/**
 * @nullable
 */
export type KatUpgradeCostMaterials = {[key: string]: number} | null;

/**
 * Information on requirements to upgrade a pet to another rarity
 */
export interface KatUpgradeCost {
  /**
   * The name of the pet
   * @nullable
   */
  name?: string | null;
  baseRarity: Tier;
  /** Time it takes to upgrade */
  hours: number;
  /** Base cost of coins it takes to do the upgrade */
  cost: number;
  /**
   * Material (if any) required to upgrade
   * @nullable
   */
  material?: string | null;
  /** Amount of Coflnet.Sky.Api.Models.KatUpgradeCost.Material required to do the upgrade */
  amount: number;
  /** @nullable */
  materials?: KatUpgradeCostMaterials;
  /**
   * Coflnet Item tag for the Pet
   * @nullable
   */
  readonly itemTag?: string | null;
}

export interface LeaderboardEntry {
  /** @nullable */
  playerUuid?: string | null;
  /** @nullable */
  playerName?: string | null;
  score: number;
  timeStamp: string;
}

/**
 * @nullable
 */
export type ListEntryFilter = {[key: string]: string | null} | null;

export interface ListEntry {
  /** @nullable */
  tag: string | null;
  /** @nullable */
  displayName: string | null;
  /** @nullable */
  filter: ListEntryFilter;
  /** @nullable */
  tags: string[] | null;
  order: number;
  /** @nullable */
  group: string | null;
  disabled: boolean;
}

export interface Listener {
  id: number;
  /**
   * Either User,auction or ItemId UserIds are +100.000
   * @maxLength 45
   * @nullable
   */
  topicId?: string | null;
  /** Price point in case of item */
  price: number;
  type: SubType;
  userId: number;
  /**
   * Additional filter to apply before sending the notification
   * @maxLength 5000
   * @nullable
   */
  filter?: string | null;
}

export interface MayorDiffFlip {
  /**
   * Item tag of the item
   * @nullable
   */
  itemTag?: string | null;
  /**
   * Item name of the item
   * @nullable
   */
  itemName?: string | null;
  /** Average absolute difference between consecutive mayor window medians */
  averageMayorMedianDiff: number;
  /** Observed volume for the item */
  volume: number;
  /** Gets or Sets ExpectedPrice */
  expectedPrice: number;
  /** Gets or Sets MedianPrice */
  medianPrice: number;
  /**
   * Gets or Sets NextMayor
   * @nullable
   */
  nextMayor?: string | null;
  usedPricesAfterCurrentMayor: boolean;
  usedPricesBeforeNextMayor: boolean;
  /**
   * Gets or Sets CurrentMayor
   * @nullable
   */
  currentMayor?: string | null;
}

export interface Member {
  rift?: Rift;
  pets_data?: PetsData;
  inventory?: Inventory;
  currencies?: Currencies;
}

/**
 * @nullable
 */
export type MemberValueValuePerCategory = {[key: string]: number} | null;

export interface MemberValue {
  fullValue: number;
  /** @nullable */
  valuePerCategory?: MemberValueValuePerCategory;
}

/**
 * @nullable
 */
export type ModSettingsHotkeys = {[key: string]: string | null} | null;

export interface ModSettings {
  justProfit: boolean;
  soundOnFlip: boolean;
  soundOnOutbid: boolean;
  blockOutbidMsg: boolean;
  shortNumbers: boolean;
  shortNames: boolean;
  blockTenSecMsg: boolean;
  /** @nullable */
  format: string | null;
  /** @nullable */
  blockedFormat: string | null;
  chat: boolean;
  countdown: boolean;
  hideNoBestFlip: boolean;
  timerX: number;
  timerY: number;
  timerSeconds: number;
  timerScale: number;
  /** @nullable */
  timerPrefix: string | null;
  timerPrecision: number;
  blockedMsg: number;
  maxPercentOfPurse: number;
  noBedDelay: boolean;
  streamerMode: boolean;
  autoStartFlipper: boolean;
  normalSoldFlips: boolean;
  tempBlacklistSpam: boolean;
  dataOnlyMode: boolean;
  ahListHours: number;
  quickSell: boolean;
  maxItemsInInventory: number;
  disableSpamProtection: boolean;
  tempBlacklistThreshold: number;
  useSellerProfileButton: boolean;
  /** @nullable */
  hotkeys: ModSettingsHotkeys;
}

/**
 * Defines the type of modification
 */
export type ModType = typeof ModType[keyof typeof ModType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModType = {
  NONE: 'NONE',
  INSERT: 'INSERT',
  REPLACE: 'REPLACE',
  APPEND: 'APPEND',
  DELETE: 'DELETE',
  HIGHLIGHT: 'HIGHLIGHT',
  SUGGEST: 'SUGGEST',
} as const;

/**
 * @nullable
 */
export type NbtDataData = {[key: string]: unknown | null} | null;

export interface NbtData {
  /** @nullable */
  data?: NbtDataData;
}

/**
 * @nullable
 */
export type NetworthBreakDownMember = {[key: string]: MemberValue} | null;

export interface NetworthBreakDown {
  fullValue: number;
  /** @nullable */
  member?: NetworthBreakDownMember;
}

export interface NotificationTarget {
  /** Primary Key for database */
  id: number;
  /**
   * The target to send the notification to
Depends on the Coflnet.Sky.Api.Models.Notifications.NotificationTarget.Type
When Type is WEBHOOK this is the url
When Type is DISCORD this is the user id to be mentioned
When Type is DISCORD_WEBHOOK this is the url
When Type is FIREBASE this is the token
When Type is EMAIL this is the email address
   * @nullable
   */
  target?: string | null;
  type: TargetType;
  when: NotifyWhen;
  /**
   * @maxLength 36
   * @nullable
   */
  userId?: string | null;
  /**
   * User Given name of this target
   * @maxLength 32
   * @nullable
   */
  name?: string | null;
  useCount: number;
}

export type NotifyWhen = typeof NotifyWhen[keyof typeof NotifyWhen];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotifyWhen = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export interface NpcFlip {
  /** @nullable */
  itemId?: string | null;
  /** @nullable */
  itemName?: string | null;
  buyPrice: number;
  npcSellPrice: number;
  profit: number;
  hourlySells: number;
  profitMargin: number;
  lastUpdated: string;
}

export interface Offer {
  isSell: boolean;
  /** @nullable */
  itemTag?: string | null;
  /** @nullable */
  itemName?: string | null;
  amount: number;
  pricePerUnit: number;
  created: string;
  /** @nullable */
  customers?: Fill[] | null;
}

export interface OldRefInfo {
  /** @nullable */
  refId: string | null;
  count: number;
  receivedTime: string;
  receivedHours: number;
  bougthPremium: number;
}

export interface Order {
  amount: number;
  pricePerUnit: number;
  orders: number;
}

export interface OwnerShip {
  expiresAt: string;
}

/**
 * @nullable
 */
export type PetExtra = {[key: string]: unknown | null} | null;

/**
 * @nullable
 */
export type PetMilestone = {[key: string]: number} | null;

export interface Pet {
  /** @nullable */
  uuid?: string | null;
  /** @nullable */
  uniqueId?: string | null;
  /** @nullable */
  type?: string | null;
  exp: number;
  active: boolean;
  /** @nullable */
  tier?: string | null;
  /** @nullable */
  heldItem?: string | null;
  candyUsed: number;
  /** @nullable */
  skin?: string | null;
  /** @nullable */
  extra?: PetExtra;
  /** @nullable */
  milestone?: PetMilestone;
  total_exp_gained: number;
}

export interface PetState {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  tier?: string | null;
  level: number;
  exp: number;
  isActive: boolean;
  /** @nullable */
  heldItem?: string | null;
  candyUsed: number;
  /** @nullable */
  colorCode?: string | null;
  /** @nullable */
  tag?: string | null;
  /** @nullable */
  uuid?: string | null;
  progressPercent: number;
  targetLevel: number;
  currentExp: number;
  expForLevel: number;
  lastUpdated: string;
}

export interface PetsData {
  autopet?: Autopet;
  /** @nullable */
  pets?: Pet[] | null;
}

export interface PlayerElectionVote {
  /** @nullable */
  votedFor?: string | null;
  voteCount: number;
}

export interface PlayerResult {
  /** @nullable */
  name: string | null;
  /** @nullable */
  uuid: string | null;
  hitCount: number;
}

export interface PlaystorTopup {
  /** @nullable */
  userId?: string | null;
}

export interface PremiumSubscription {
  /** @nullable */
  externalId?: string | null;
  /** @nullable */
  endsAt?: string | null;
  /** @nullable */
  productName?: string | null;
  /** @nullable */
  paymentAmount?: string | null;
  renewsAt: string;
  createdAt: string;
}

export interface PriceEstimate {
  /** The best matching lowest bin found on ah */
  lbin: number;
  /** The best matching median sell price */
  median: number;
  /** average 24 hour sell volume */
  volume: number;
  /**
   * The link to best matching lbin
   * @nullable
   */
  lbinLink?: string | null;
  /** Suggested price for selling withing 5 minutes */
  fastSell: number;
  /**
   * They key for the lbin
   * @nullable
   */
  lbinKey?: string | null;
  /**
   * The key of the median price
   * @nullable
   */
  medianKey?: string | null;
  /**
   * The key of the
   * @nullable
   */
  itemKey?: string | null;
}

export interface PriceStatistics {
  averageSellTimeSeconds: number;
  totalAuctionsSold: number;
  totalListed: number;
  totalSellers: number;
  totalBuyers: number;
  totalBids: number;
  totalCoinsTransferred: number;
  totalAuctions: number;
  totalItemsSold: number;
  binCount: number;
  /** @nullable */
  prices?: AveragePrice[] | null;
  /** @nullable */
  recentSamples?: AuctionPreview[] | null;
}

export interface PriceSumary {
  min: number;
  median: number;
  mean: number;
  mode: number;
  volume: number;
  max: number;
}

export interface PricingBreakdwon {
  /** @nullable */
  craftPrice: CraftPrice[] | null;
}

export interface PricingRequest {
  /** @nullable */
  productSlugs?: string[] | null;
  /** @nullable */
  countryCode?: string | null;
  /** @nullable */
  creatorCode?: string | null;
}

export interface PrivacySettings {
  /** @nullable */
  chatRegex: string | null;
  collectChat: boolean;
  collectInventory: boolean;
  disableTradeStoring: boolean;
  disableKuudraTracking: boolean;
  disableBazaarTracking: boolean;
  collectTab: boolean;
  collectScoreboard: boolean;
  allowProxy: boolean;
  collectChatClicks: boolean;
  extendDescriptions: boolean;
  /** @nullable */
  commandPrefixes: string[] | null;
  autoStart: boolean;
  /** @nullable */
  chatBlockRegex: string | null;
  noMessageBlocking: boolean;
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  [key: string]: unknown;
}

export interface ProductPricingResponse {
  /** @nullable */
  productSlug?: string | null;
  /** @nullable */
  creatorCode?: string | null;
  discountPercent: number;
  /** @nullable */
  providers?: ProviderPricingOption[] | null;
}

export type ProductType = typeof ProductType[keyof typeof ProductType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductType = {
  NONE: 'NONE',
  SERVICE: 'SERVICE',
  COLLECTABLE: 'COLLECTABLE',
  TOP_UP: 'TOP_UP',
  LOCKED: 'LOCKED',
  DISABLED: 'DISABLED',
  VARIABLE_PRICE: 'VARIABLE_PRICE',
} as const;

/**
 * @nullable
 */
export type ProfileMembers = {[key: string]: Member} | null;

export interface Profile {
  /** @nullable */
  profile_id?: string | null;
  /** @nullable */
  members?: ProfileMembers;
  /** @nullable */
  cute_name?: string | null;
  selected: boolean;
  /** @nullable */
  game_mode?: string | null;
  banking?: Banking;
  /** @nullable */
  created_at?: number | null;
}

export interface ProfitableCraft {
  /** @nullable */
  itemId?: string | null;
  /** @nullable */
  itemName?: string | null;
  sellPrice: number;
  craftCost: number;
  buyOrderCraftCost: number;
  /** @nullable */
  ingredients?: Ingredient[] | null;
  reqCollection?: RequiredCollection;
  reqSlayer?: RequiredCollection;
  reqSkill?: RequiredSkill;
  /** @nullable */
  type?: string | null;
  volume: number;
  median: number;
  lastUpdated: string;
}

export interface PropertyChange {
  /** @nullable */
  description: string | null;
  effect: number;
}

export interface ProviderPricingOption {
  /** @nullable */
  providerSlug?: string | null;
  /** @nullable */
  providerName?: string | null;
  originalPrice: number;
  discountedPrice: number;
  discountAmount: number;
  /** @nullable */
  currencyCode?: string | null;
  coinsAmount: number;
  /** @nullable */
  productTitle?: string | null;
  /** @nullable */
  productDescription?: string | null;
  /** @nullable */
  googlePlayProductId?: string | null;
}

export interface PublicSubscription {
  sourceType?: SourceType;
  id: number;
  /** @nullable */
  sourceSubIdRegex?: string | null;
  /** @nullable */
  targets?: TargetLink[] | null;
}

/**
 * Arguments for purchasing a service
 */
export interface PurchaseArgs {
  /**
   * The service to pruchase
   * @nullable
   */
  slug: string | null;
  /** How many instances to purchase (longer time) */
  count: number;
  /**
   * Reference to prevent dupplicates
   * @nullable
   */
  reference: string | null;
}

/**
 * What status the query has
 */
export type QueryStatus = typeof QueryStatus[keyof typeof QueryStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QueryStatus = {
  Success: 'Success',
  NoResults: 'NoResults',
  Pending: 'Pending',
  Partial: 'Partial',
} as const;

export interface Recipe {
  /** @nullable */
  A1: string | null;
  /** @nullable */
  A2: string | null;
  /** @nullable */
  A3: string | null;
  /** @nullable */
  B1: string | null;
  /** @nullable */
  B2: string | null;
  /** @nullable */
  B3: string | null;
  /** @nullable */
  C1: string | null;
  /** @nullable */
  C2: string | null;
  /** @nullable */
  C3: string | null;
  count: number;
}

export interface ReferralInfo {
  referedCount: number;
  validatedMinecraft: number;
  purchasedCoins: number;
  purchasedCoinAmount: number;
  /** @nullable */
  referredBy?: string | null;
  /** @nullable */
  inviterMinecraftName?: string | null;
  oldInfo?: OldRefInfo;
}

/**
 * Object containing referral code to give reward to
 */
export interface ReferredBy {
  /** @nullable */
  refCode?: string | null;
}

export type Reforge = typeof Reforge[keyof typeof Reforge];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Reforge = {
  None: 'None',
  Demonic: 'Demonic',
  Forceful: 'Forceful',
  Gentle: 'Gentle',
  Godly: 'Godly',
  Hurtful: 'Hurtful',
  Keen: 'Keen',
  Strong: 'Strong',
  Superior: 'Superior',
  Unpleasant: 'Unpleasant',
  Zealous: 'Zealous',
  Odd: 'Odd',
  Rich: 'Rich',
  Epic: 'Epic',
  Fair: 'Fair',
  Fast: 'Fast',
  Heroic: 'Heroic',
  Legendary: 'Legendary',
  Spicy: 'Spicy',
  Deadly: 'Deadly',
  Fine: 'Fine',
  Grand: 'Grand',
  Hasty: 'Hasty',
  Neat: 'Neat',
  Papid: 'Papid',
  Unreal: 'Unreal',
  Clean: 'Clean',
  Fierce: 'Fierce',
  Heavy: 'Heavy',
  Light: 'Light',
  Mythic: 'Mythic',
  Pure: 'Pure',
  Smart: 'Smart',
  Titanic: 'Titanic',
  Wise: 'Wise',
  Very: 'Very',
  Highly: 'Highly',
  Bizarre: 'Bizarre',
  Itchy: 'Itchy',
  Omnious: 'Omnious',
  Pleasant: 'Pleasant',
  Pretty: 'Pretty',
  Shiny: 'Shiny',
  Simple: 'Simple',
  Strange: 'Strange',
  Vivid: 'Vivid',
  Ominous: 'Ominous',
  Sharp: 'Sharp',
  Rapid: 'Rapid',
  Necrotic: 'Necrotic',
  Fabled: 'Fabled',
  Precise: 'Precise',
  Giant: 'Giant',
  warped_on_aote: 'warped_on_aote',
  Spiritual: 'Spiritual',
  Treacherous: 'Treacherous',
  RENOWED: 'RENOWED',
  Reinforced: 'Reinforced',
  rich_bow: 'rich_bow',
  Spiked: 'Spiked',
  Perfect: 'Perfect',
  Magnetic: 'Magnetic',
  Loving: 'Loving',
  Gilded: 'Gilded',
  odd_sword: 'odd_sword',
  Salty: 'Salty',
  Silky: 'Silky',
  Refined: 'Refined',
  suspicious: 'suspicious',
  toil: 'toil',
  empowered: 'empowered',
  fruitful: 'fruitful',
  blessed: 'blessed',
  shaded: 'shaded',
  awkward: 'awkward',
  dirty: 'dirty',
  undead: 'undead',
  cubic: 'cubic',
  bloody: 'bloody',
  moil: 'moil',
  ridiculous: 'ridiculous',
  rich_sword: 'rich_sword',
  warped: 'warped',
  odd_bow: 'odd_bow',
  candied: 'candied',
  submerged: 'submerged',
  ancient: 'ancient',
  withered: 'withered',
  sweet: 'sweet',
  fleet: 'fleet',
  stellar: 'stellar',
  mithraic: 'mithraic',
  Auspicious: 'Auspicious',
  headstrong: 'headstrong',
  stiff: 'stiff',
  bulky: 'bulky',
  lucky: 'lucky',
  bountiful: 'bountiful',
  heated: 'heated',
  jaded: 'jaded',
  ambered: 'ambered',
  double_bit: 'double_bit',
  excellent: 'excellent',
  fortunate: 'fortunate',
  prospector: 'prospector',
  lush: 'lush',
  sturdy: 'sturdy',
  lumberjack: 'lumberjack',
  unyielding: 'unyielding',
  great: 'great',
  robust: 'robust',
  rugged: 'rugged',
  zooming: 'zooming',
  peasant: 'peasant',
  strengthened: 'strengthened',
  glistening: 'glistening',
  waxed: 'waxed',
  fortified: 'fortified',
  green_thumb: 'green_thumb',
  pitchin: 'pitchin',
  coldfusion: 'coldfusion',
  bustling: 'bustling',
  earthy: 'earthy',
  mossy: 'mossy',
  blooming: 'blooming',
  rooted: 'rooted',
  festive: 'festive',
  snowy: 'snowy',
  Unknown: 'Unknown',
  Any: 'Any',
  chomp: 'chomp',
  full_jaw_fanging_kit: 'full_jaw_fanging_kit',
  presumed_gallon_of_red_paint: 'presumed_gallon_of_red_paint',
  displaced_leech: 'displaced_leech',
  Fang_tastic_chocolate_chip: 'Fang_tastic_chocolate_chip',
  bubba_blister: 'bubba_blister',
  fanged: 'fanged',
  blood_soaked: 'blood_soaked',
  stained: 'stained',
  menacing: 'menacing',
  hefty: 'hefty',
  soft: 'soft',
  honored: 'honored',
  blended: 'blended',
  astute: 'astute',
  colossal: 'colossal',
  brilliant: 'brilliant',
  greater_spook: 'greater_spook',
  beady: 'beady',
  buzzing: 'buzzing',
  jerry_stone: 'jerry_stone',
  hyper: 'hyper',
  coldfused: 'coldfused',
  Earthly: 'Earthly',
  glacial: 'glacial',
  lustrous: 'lustrous',
  blazing: 'blazing',
  scraped: 'scraped',
  royal: 'royal',
  dimensional: 'dimensional',
  squeaky: 'squeaky',
  trashy: 'trashy',
  calcified: 'calcified',
  groovy: 'groovy',
  moonglade: 'moonglade',
  bloodshot: 'bloodshot',
  blood_shot: 'blood_shot',
  erudite: 'erudite',
  lunar: 'lunar',
  sunny: 'sunny',
  mantid: 'mantid',
} as const;

export interface RequiredCollection {
  /** @nullable */
  name?: string | null;
  level: number;
}

export interface RequiredSkill {
  /** @nullable */
  name?: string | null;
  level: number;
}

export interface ReverseNpcFlip {
  /** @nullable */
  npcName?: string | null;
  /** @nullable */
  itemId?: string | null;
  /** @nullable */
  itemName?: string | null;
  npcBuyPrice: number;
  sellPrice: number;
  profit: number;
  profitMargin: number;
  /** @nullable */
  costs?: Cost[] | null;
  volume: number;
  lastUpdated: string;
}

export interface Rift {
  inventory?: Inventory;
}

/**
 * @nullable
 */
export type SaveAuctionFlatNbt = {[key: string]: string | null} | null;

export interface SaveAuction {
  /** @nullable */
  uuid?: string | null;
  count: number;
  startingBid: number;
  /**
   * @maxLength 40
   * @nullable
   */
  tag?: string | null;
  /**
   * @maxLength 45
   * @nullable
   */
  itemName?: string | null;
  start: string;
  end: string;
  /** @nullable */
  auctioneerId?: string | null;
  /** @nullable */
  profileId?: string | null;
  /** @nullable */
  coop?: string[] | null;
  /** @nullable */
  coopMembers?: UuId[] | null;
  highestBidAmount: number;
  /** @nullable */
  bids?: SaveBids[] | null;
  anvilUses: number;
  /** @nullable */
  enchantments?: Enchantment[] | null;
  nbtData?: NbtData;
  itemCreatedAt: string;
  reforge: Reforge;
  category: Category;
  tier: Tier;
  bin: boolean;
  /** @nullable */
  flatNbt: SaveAuctionFlatNbt;
}

export interface SaveBids {
  /** @nullable */
  bidder?: string | null;
  /** @nullable */
  profileId?: string | null;
  amount: number;
  timestamp: string;
}

export interface SearchResultItem {
  /** @nullable */
  name: string | null;
  /** @nullable */
  id: string | null;
  /** @nullable */
  type: string | null;
  /** @nullable */
  iconUrl: string | null;
  /** @nullable */
  img: string | null;
  tier: Tier;
}

export interface SellSpeedBucket {
  minPrice: number;
  maxPrice: number;
  avgPrice: number;
  avgSellTimeSeconds: number;
  /** @nullable */
  speedCategory?: string | null;
  sampleCount: number;
}

export interface SellerShare {
  /** @nullable */
  seller?: string | null;
  count: number;
  percentage: number;
}

export interface SkyblockItem {
  npcSellPrice: number;
  /** @nullable */
  minecraftType?: string | null;
  /** @nullable */
  iconUrl?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  tag?: string | null;
  flags?: ItemFlags;
  tier?: Tier;
  category?: ItemCategory;
}

/**
 * @nullable
 */
export type SoldAuctionFlattenedNbt = {[key: string]: string | null} | null;

/**
 * Auction with NBT data encoded as base64 string for API responses
 */
export interface SoldAuction {
  /** Auction ID */
  id: number;
  /**
   * Auction UUID
   * @nullable
   */
  uuid?: string | null;
  /**
   * Item tag/ID
   * @nullable
   */
  tag?: string | null;
  /**
   * Item name
   * @nullable
   */
  itemName?: string | null;
  /**
   * Auctioneer UUID
   * @nullable
   */
  auctioneerId?: string | null;
  /** Starting bid amount */
  startingBid: number;
  /** Highest bid amount */
  highestBidAmount: number;
  /** Auction start time */
  start: string;
  /** Auction end time */
  end: string;
  /** Is BIN auction */
  bin: boolean;
  /** Item count */
  count: number;
  /**
   * Enchantments
   * @nullable
   */
  enchantments?: Enchantment[] | null;
  /**
   * NBT data as base64 encoded string
   * @nullable
   */
  shortItemBytes?: string | null;
  /** @nullable */
  readonly flattenedNbt?: SoldAuctionFlattenedNbt;
  tier: Tier;
}

export type SourceType = typeof SourceType[keyof typeof SourceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SourceType = {
  Unknwon: 'Unknwon',
  Any: 'Any',
  Bazaar: 'Bazaar',
  BazaarExpire: 'BazaarExpire',
  Subscription: 'Subscription',
  Purchase: 'Purchase',
  McVerify: 'McVerify',
} as const;

/**
 * Item Metadata
 */
export interface SpreadFlip {
  flip?: BazaarFlip;
  /** @nullable */
  itemName?: string | null;
  isManipulated: boolean;
}

export interface StorageQuickStatus {
  /** @nullable */
  productId?: string | null;
  buyPrice: number;
  buyVolume: number;
  buyMovingWeek: number;
  buyOrdersCount: number;
  sellPrice: number;
  sellVolume: number;
  sellMovingWeek: number;
  sellOrdersCount: number;
  timeStamp: string;
  /** @nullable */
  buyOrders?: Order[] | null;
  /** @nullable */
  sellOrders?: Order[] | null;
}

export type SubType = typeof SubType[keyof typeof SubType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_4: 4,
  NUMBER_8: 8,
  NUMBER_16: 16,
  NUMBER_32: 32,
  NUMBER_64: 64,
  NUMBER_128: 128,
  NUMBER_256: 256,
  NUMBER_512: 512,
} as const;

/**
 * Element for the /lowSupply page
 */
export interface SupplyElement {
  /**
   * Item Tag of the time
   * @nullable
   */
  tag: string | null;
  /** How much supply there is on the ah */
  supply: number;
  /** Median sell price */
  median: number;
  lbinData: BinResponse;
  /** The average amount of sells in 24 hours */
  volume: number;
}

export interface TargetLink {
  /** @nullable */
  name?: string | null;
  id: number;
  priority: number;
  isDisabled: boolean;
}

export type TargetType = typeof TargetType[keyof typeof TargetType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TargetType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
} as const;

export type Tier = typeof Tier[keyof typeof Tier];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Tier = {
  UNKNOWN: 'UNKNOWN',
  COMMON: 'COMMON',
  UNCOMMON: 'UNCOMMON',
  RARE: 'RARE',
  EPIC: 'EPIC',
  LEGENDARY: 'LEGENDARY',
  SPECIAL: 'SPECIAL',
  VERY_SPECIAL: 'VERY_SPECIAL',
  MYTHIC: 'MYTHIC',
  DIVINE: 'DIVINE',
  ULTIMATE: 'ULTIMATE',
} as const;

/**
 * Additional arguments for a topup
 */
export interface TopUpArguments {
  /** A specific amount of coins to topup */
  coinAmount: number;
  /**
   * The url to redirect to after successful payment
   * @nullable
   */
  successUrl?: string | null;
  /**
   * The url to redirect to when user aborts payment
   * @nullable
   */
  cancelUrl?: string | null;
  /**
   * An optional creator code to apply to the purchase
   * @nullable
   */
  creatorCode?: string | null;
  /**
   * An optional discount code to apply to the purchase
   * @nullable
   */
  discountcode?: string | null;
}

export interface TopUpIdResponse {
  /** @nullable */
  id?: string | null;
  /**
   * @deprecated
   * @nullable
   */
  dirctLink?: string | null;
  /** @nullable */
  directLink?: string | null;
}

export interface TopUpProduct {
  type?: ProductType;
  price: number;
  /** @nullable */
  currencyCode?: string | null;
  /** @nullable */
  providerSlug?: string | null;
  id: number;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  slug?: string | null;
  /** @nullable */
  description?: string | null;
  cost: number;
  ownershipSeconds: number;
}

export interface TradeRequest {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  playerUuid?: string | null;
  /** @nullable */
  playerName?: string | null;
  /** @nullable */
  buyerUuid?: string | null;
  item?: Item;
  /**
   * The amount of coins the player wants to spend
   * @nullable
   */
  coins?: number | null;
  /** @nullable */
  wantedItems?: WantedItem[] | null;
  timestamp: string;
}

export interface UuId {
  id: number;
  /** @nullable */
  value?: string | null;
}

export interface ValidatedDiscount {
  /** @nullable */
  code?: string | null;
  /** @nullable */
  id?: string | null;
  amount: number;
  /** @nullable */
  amountType?: string | null;
  /** @nullable */
  name?: string | null;
  isValid: boolean;
  isLimitedToProducts: boolean;
  isSubscriptionOnly: boolean;
  /** @nullable */
  duration?: string | null;
  durationInMonths: number;
}

export interface VisibilitySettings {
  cost: boolean;
  estProfit: boolean;
  lbin: boolean;
  slbin: boolean;
  medPrice: boolean;
  seller: boolean;
  volume: boolean;
  extraFields: number;
  avgSellTime: boolean;
  profitPercent: boolean;
  profit: boolean;
  sellerOpenBtn: boolean;
  lore: boolean;
  links: boolean;
  copySuccessMessage: boolean;
  hideSold: boolean;
  hideManipulated: boolean;
}

export interface VolumeBucket {
  minPrice: number;
  maxPrice: number;
  avgPrice: number;
  count: number;
}

/**
 * @nullable
 */
export type WantedItemFilters = {[key: string]: string | null} | null;

export interface WantedItem {
  /** @nullable */
  tag?: string | null;
  /** @nullable */
  itemName?: string | null;
  /** @nullable */
  filters?: WantedItemFilters;
}

export type GetApiAuctionRandomParams = {
token?: string;
};

export type GetApiAuctionsTagItemTagActiveBinParams = {
/**
 * Filters for the auctions
 */
query?: {[key: string]: string};
};

export type GetApiAuctionsTagItemTagSoldParams = {
/**
 * Page of auctions to get
 */
page?: number;
/**
 * how many auctions to get per page 1-1000
 */
pageSize?: number;
/**
 * Partner token to get more data
 */
token?: string;
};

export type GetApiAuctionsBatchParams = {
/**
 * Page of auctions to get
 */
page?: string;
tag?: string;
/**
 * Secret token to access data
 */
token?: string;
count?: number;
};

export type GetApiAuctionsTagItemTagRecentOverviewParams = {
query?: {[key: string]: string};
};

export type GetApiAuctionsTagItemTagArchiveOverviewParams = {
query?: {[key: string]: string};
};

export type GetApiAuctionsTagItemTagActiveOverviewParams = {
query?: {[key: string]: string};
};

export type PostApiAuctionsUidsSold200One = {[key: string]: ItemSell[]};

export type PostApiAuctionsUidsSold200Two = {[key: string]: ItemSell[]};

export type PostApiAuctionsUidsSold200Three = {[key: string]: ItemSell[]};

export type GetApiBazaarItemTagHistoryParams = {
start?: string;
end?: string;
};

export type GetApiBazaarItemTagSnapshotParams = {
/**
 * Whattime to retrieve the information at (defaults to now)
 */
timestamp?: string;
};

export type GetApiBazaarItemTagExportParams = {
start?: string;
end?: string;
fullOrderBook?: boolean;
};

export type GetApiCraftProfitParams = {
player?: string;
profile?: string;
};

export type PostApiDataPlayerNameParams = {
name?: string;
source?: string;
};

export type PostApiDataPlayerNamesParams = {
source?: string;
};

export type GetApiFlipAttributeParams = {
/**
 * Optional sort key: profit, price, volume, age
 */
sort?: string;
};

export type GetApiFlipAttribute401One = {
  message?: string;
};

export type GetApiFlipBazaarSpreadDeemand401One = {
  message?: string;
};

export type GetApiFlipMayor401One = {
  message?: string;
};

export type GetApiFlipNpcReverseParams = {
requestRefresh?: boolean;
};

export type GetApiFlipNpcReverse401One = {
  message?: string;
};

export type GetApiFlipFusionMultistep401One = {
  message?: string;
};

export type GetApiFlipForgeParams = {
uuid?: string;
};

export type PostApiFlipTrackPurchaseAuctionIdParams = {
/**
 * Identifier of finder
 */
finder?: string;
/**
 * The uuid of the player
 */
playerId?: string;
/**
 * Sugested target price
 */
price?: number;
/**
 * Unix millisecond timestamp when the flip was found
 */
timeStamp?: number;
};

export type PostApiFlipTrackFoundAuctionIdParams = {
/**
 * Identifier of finder
 */
finder?: string;
/**
 * Suggested target price
 */
price?: number;
/**
 * Unix millisecond timestamp when the flip was found
 */
timeStamp?: number;
};

export type GetApiFlipStatsPlayerPlayerUuidParams = {
start?: string;
/**
 * The end time to retrieve
 */
end?: string;
};

export type GetApiFlipStatsFinderFinderNameParams = {
/**
 * The start time of flips to get (inclusive)
 */
start?: string;
/**
 * The end time of flips to get (exclusive)
 */
end?: string;
};

export type GetApiFlipUnknownParams = {
end?: string;
};

export type GetApiDataAiParams = {
prompt?: string;
};

export type PostApiItemsNames200One = {[key: string]: string};

export type PostApiItemsNames200Two = {[key: string]: string};

export type PostApiItemsNames200Three = {[key: string]: string};

export type GetApiLeaderboardProfitParams = {
weekOffset?: number;
};

export type GetApiMayorParams = {
/**
 * Start ISO 8601
 */
from?: string;
/**
 * End eg. 2022-09-22T20:03:10.937Z
 */
to?: string;
};

export type PostApiModAuthParams = {
newId?: string;
};

export type PostApiModAuth401One = {
  message?: string;
};

export type GetApiModItemUuidParams = {
count?: number;
};

export type GetApiNotificationsTargets401One = {
  message?: string;
};

export type PostApiNotificationsTargets401One = {
  message?: string;
};

export type DeleteApiNotificationsTargets401One = {
  message?: string;
};

export type PutApiNotificationsTargets401One = {
  message?: string;
};

export type GetApiNotificationsSubscriptions401One = {
  message?: string;
};

export type PostApiNotificationsSubscriptions401One = {
  message?: string;
};

export type DeleteApiNotificationsSubscriptions401One = {
  message?: string;
};

export type PutApiNotificationsSubscriptions401One = {
  message?: string;
};

export type PostApiNotificationsTargetsTest401One = {
  message?: string;
};

export type PostApiNotificationsListeners401One = {
  message?: string;
};

export type GetApiNotificationsListeners401One = {
  message?: string;
};

export type DeleteApiNotificationsListeners401One = {
  message?: string;
};

export type GetApiPlayerPlayerUuidBidsParams = {
/**
 * Page of auctions (another 10)
 */
page?: number;
filters?: {[key: string]: string};
};

export type GetApiPlayerPlayerUuidAuctionsParams = {
/**
 * Page of auctions (another 10)
 */
page?: number;
filters?: {[key: string]: string};
};

export type PostApiPlayerNames200One = {[key: string]: string};

export type PostApiPlayerNames200Two = {[key: string]: string};

export type PostApiPlayerNames200Three = {[key: string]: string};

export type GetApiPlayerBazaarOrdersParams = {
apiKey?: string;
};

export type GetApiPlayerBazaarFlipsParams = {
/**
 * Key generated from /cofl api in game
 */
apiKey?: string;
};

export type GetApiPlayerExtractedParams = {
apiKey?: string;
};

export type PostApiTopupStripeProductSlug401One = {
  message?: string;
};

export type PostApiTopupPaypalProductSlug401One = {
  message?: string;
};

export type PostApiTopupPlaystore401One = {
  message?: string;
};

export type PostApiTopupRates401One = {
  message?: string;
};

export type PostApiTopupLemonsqueezyProductSlug401One = {
  message?: string;
};

export type GetApiLinkvertiseParams = {
hash?: string;
email?: string;
};

export type PostApiServicePurchase401One = {
  message?: string;
};

export type PostApiPremiumPricesAdjusted401One = {
  message?: string;
};

export type PostApiPremiumUserOwns200One = {[key: string]: OwnerShip};

export type PostApiPremiumUserOwns200Two = {[key: string]: OwnerShip};

export type PostApiPremiumUserOwns200Three = {[key: string]: OwnerShip};

export type PostApiPremiumUserOwns401One = {
  message?: string;
};

export type GetApiPremiumTransactions401One = {
  message?: string;
};

export type PostApiPremiumSubscriptionSubscriptionSlugParams = {
creatorCode?: string;
discountcode?: string;
};

export type PostApiPremiumSubscriptionSubscriptionSlug401One = {
  message?: string;
};

export type GetApiPremiumSubscription401One = {
  message?: string;
};

export type DeleteApiPremiumSubscriptionExternalId401One = {
  message?: string;
};

export type PutApiPremiumSubscriptionExternalIdReactivate401One = {
  message?: string;
};

export type PutApiPremiumSubscriptionExternalIdSwitchParams = {
targetProductSlug?: string;
};

export type PutApiPremiumSubscriptionExternalIdSwitch401One = {
  message?: string;
};

export type GetApiItemPriceItemTagParams = {
/**
 * Filter parameters - can be added directly as query parameters (e.g., ?Reforge=Legendary&Rarity=EPIC)
 */
filters?: {[key: string]: string};
};

export type GetApiItemPriceItemTagBinParams = {
/**
 * Filter parameters - can be added directly as query parameters
 */
filters?: {[key: string]: string};
};

export type GetApiItemPriceItemTagCurrentParams = {
/**
 * How many items to search for (and include in cost)
 */
count?: number;
};

export type GetApiItemPriceItemTagHistoryDayParams = {
/**
 * Filter parameters - can be added directly as query parameters
 */
filters?: {[key: string]: string};
};

export type GetApiItemPriceItemTagHistoryWeekParams = {
/**
 * Filter parameters - can be added directly as query parameters
 */
filters?: {[key: string]: string};
};

export type GetApiItemPriceItemTagHistoryMonthParams = {
/**
 * Filter parameters - can be added directly as query parameters
 */
filters?: {[key: string]: string};
};

export type GetApiItemPriceItemTagHistoryYearParams = {
/**
 * Filter parameters - can be added directly as query parameters
 */
filters?: {[key: string]: string};
};

export type GetApiItemPriceItemTagHistoryYear401One = {
  message?: string;
};

export type GetApiItemPriceItemTagAnalysisParams = {
days?: number;
filters?: {[key: string]: string};
};

export type GetApiFilterOptionsParams = {
itemTag?: string;
};

export type PostApiItemFilters200One = {[key: string]: string};

export type PostApiItemFilters200Two = {[key: string]: string};

export type PostApiItemFilters200Three = {[key: string]: string};

export type GetApiPricesNeu200One = {[key: string]: number};

export type GetApiPricesNeu200Two = {[key: string]: number};

export type GetApiPricesNeu200Three = {[key: string]: number};

export type GetApiPricesChangeParams = {
itemTags?: string[];
};

export type GetApiPricesChange200One = {[key: string]: DropStatistic};

export type GetApiPricesChange200Two = {[key: string]: DropStatistic};

export type GetApiPricesChange200Three = {[key: string]: DropStatistic};

export type GetApiPriceAttributes200One = {[key: string]: {[key: string]: number}};

export type GetApiPriceAttributes200Two = {[key: string]: {[key: string]: number}};

export type GetApiPriceAttributes200Three = {[key: string]: {[key: string]: number}};

export type PostApiProfileItems200One = {[key: string]: SaveAuction[]};

export type PostApiProfileItems200Two = {[key: string]: SaveAuction[]};

export type PostApiProfileItems200Three = {[key: string]: SaveAuction[]};

export type PostApiReferralReferredBy401One = {
  message?: string;
};

export type GetApiReferralInfo401One = {
  message?: string;
};

export type GetApiItemSearchSearchValParams = {
/**
 * How many results to return
 */
expectedResults?: number;
};

export type GetApiSearchSearchValParams = {
/**
 * The maximum amount of results to return
 */
limit?: number;
};

export type GetApiInventory401One = {
  message?: string;
};

export type PostApiTrades401One = {
  message?: string;
};

export type GetApiTradesParams = {
page?: number;
pageSize?: number;
};

export type GetApiTradesBodyOne = {[key: string]: string};

export type GetApiTradesBodyTwo = {[key: string]: string};

export type GetApiTradesBodyThree = {[key: string]: string};

export type GetApiTradesBodyFour = {[key: string]: string};

export type DeleteApiTradesId401One = {
  message?: string;
};

export type GetApiTradesOwn401One = {
  message?: string;
};

export type GetApiUserPrivacy401One = {
  message?: string;
};

export type PostApiUserPrivacy401One = {
  message?: string;
};

