name: Cypress Tests
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
jobs:
  cypress-run:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    env:
      TEST_RUNNER: "true"
      NEXT_PUBLIC_TEST_RUNNER: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses : actions/setup-node@v6
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: build app
        run: npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          start: npm start
